# Generated by Django 4.2.5 on 2023-10-05 18:47

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(auto_created=builtins.id, primary_key=True, serialize=False),
        ),
    ]
